/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Administrators;

import Connections.AddDataProcedures;
import GUI.LoginProvince;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gabriel
 */
public class AmountCollectedDrugStore extends javax.swing.JFrame {

    /**
     * Creates new form AmountCollectedDrugStore
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public AmountCollectedDrugStore() throws SQLException, ClassNotFoundException {
        initComponents();
        if (LoginProvince.logInProvince==1){
            updateCollectedAmountSanJose();
        }
        if (LoginProvince.logInProvince==3){
            updateCollectedAmountCartago();
        }
        if(LoginProvince.logInProvince==4){
            updateCollectedAmountHeredia();
        }
    }
    
    private void updateCollectedAmountSanJose() throws SQLException, ClassNotFoundException{
        double amountSanJose  = AddDataProcedures.consultAmountSanJoseDrugStore();
        collectedAmount.setText("$"+String.valueOf(amountSanJose));
    }
    private void updateCollectedAmountCartago() throws SQLException, ClassNotFoundException{
        double amountSanJose  = AddDataProcedures.consultAmountCartagoDrugStore();
        collectedAmount.setText("$"+String.valueOf(amountSanJose));
    }
    private void updateCollectedAmountHeredia() throws SQLException, ClassNotFoundException{
        double amountSanJose  = AddDataProcedures.consultAmountHerediaDrugStore();
        collectedAmount.setText("$"+String.valueOf(amountSanJose));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        collectedAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Total revenue collected from pharmacies");

        collectedAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        collectedAmount.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(collectedAmount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(collectedAmount)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel collectedAmount;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
