/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Employees;

import GUI.signIn;

/**
 *
 * @author Andrés Pérez Bonilla
 */
public class EmployeeModule extends javax.swing.JFrame {

    /**
     * Creates new form Employye
     */
    public EmployeeModule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        employeeModuleRegisterOrder = new javax.swing.JButton();
        employeeModuleModifyOrder = new javax.swing.JButton();
        employeeModuleRegisterClient = new javax.swing.JButton();
        employeeModuleRegisterMedicine = new javax.swing.JButton();
        employeeModuleConsultOrder = new javax.swing.JButton();
        employeeModuleBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Module");

        employeeModuleRegisterOrder.setText("Register Order");
        employeeModuleRegisterOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeModuleRegisterOrderActionPerformed(evt);
            }
        });

        employeeModuleModifyOrder.setText("Modify Order");
        employeeModuleModifyOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeModuleModifyOrderActionPerformed(evt);
            }
        });

        employeeModuleRegisterClient.setText("Register Client");
        employeeModuleRegisterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeModuleRegisterClientActionPerformed(evt);
            }
        });

        employeeModuleRegisterMedicine.setText("Register Medicine");
        employeeModuleRegisterMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeModuleRegisterMedicineActionPerformed(evt);
            }
        });

        employeeModuleConsultOrder.setText("Consult Order");
        employeeModuleConsultOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeModuleConsultOrderActionPerformed(evt);
            }
        });

        employeeModuleBack.setText("Back");
        employeeModuleBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeModuleBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeeModuleRegisterOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(employeeModuleConsultOrder)
                        .addComponent(employeeModuleModifyOrder))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(employeeModuleRegisterClient))
                            .addComponent(employeeModuleRegisterMedicine)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(employeeModuleBack)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(employeeModuleRegisterOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeModuleModifyOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeModuleConsultOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeModuleRegisterMedicine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeModuleRegisterClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeModuleBack)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeModuleRegisterOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeModuleRegisterOrderActionPerformed
        RegisterOrder registerOrder = new RegisterOrder();
        registerOrder.setVisible(true);
        registerOrder.setLocationRelativeTo(null);
        registerOrder.setDefaultCloseOperation(RegisterOrder.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_employeeModuleRegisterOrderActionPerformed

    private void employeeModuleRegisterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeModuleRegisterClientActionPerformed
        // TODO add your handling code here:
        RegisterClient registerClient = new RegisterClient();
        registerClient.setVisible(true);
        registerClient.setLocationRelativeTo(null);
        registerClient.setDefaultCloseOperation(RegisterClient.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_employeeModuleRegisterClientActionPerformed

    private void employeeModuleConsultOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeModuleConsultOrderActionPerformed
        // TODO add your handling code here:
        ConsultOrder consultOrder = new ConsultOrder();
        consultOrder.setVisible(true);
        consultOrder.setLocationRelativeTo(null);
        consultOrder.setDefaultCloseOperation(ConsultOrder.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_employeeModuleConsultOrderActionPerformed

    private void employeeModuleBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeModuleBackActionPerformed
        // TODO add your handling code here:
        signIn signIn = new signIn();
        signIn.setVisible(true);
        signIn.setLocationRelativeTo(null);
        signIn.setDefaultCloseOperation(signIn.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_employeeModuleBackActionPerformed

    private void employeeModuleModifyOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeModuleModifyOrderActionPerformed
        // TODO add your handling code here:
        ModifyOrder modifyOrder = new ModifyOrder();
        modifyOrder.setVisible(true);
        modifyOrder.setLocationRelativeTo(null);
        modifyOrder.setDefaultCloseOperation(ModifyOrder.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_employeeModuleModifyOrderActionPerformed

    private void employeeModuleRegisterMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeModuleRegisterMedicineActionPerformed
        // TODO add your handling code here:
        RegisterMedicine registerMedicine = new RegisterMedicine();
        registerMedicine.setVisible(true);
        registerMedicine.setLocationRelativeTo(null);
        registerMedicine.setDefaultCloseOperation(RegisterMedicine.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_employeeModuleRegisterMedicineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeeModuleBack;
    private javax.swing.JButton employeeModuleConsultOrder;
    private javax.swing.JButton employeeModuleModifyOrder;
    private javax.swing.JButton employeeModuleRegisterClient;
    private javax.swing.JButton employeeModuleRegisterMedicine;
    private javax.swing.JButton employeeModuleRegisterOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
