/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Clients;

import Connections.ConnectionSQL;
import GUI.signIn;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrés Pérez Bonilla
 */
public class clientModule extends javax.swing.JFrame {
    
    private static ResultSet res;

    /**
     * Creates new form clientModule
     */
    public clientModule() throws ClassNotFoundException {
        initComponents();
        loadOrdersTable(784531234);
    }
    
    public void loadOrdersTable(int idClient) throws ClassNotFoundException{
        DefaultTableModel model = (DefaultTableModel) orderList.getModel();
        model.setRowCount(0);
        res=ConnectionSQL.createConsult("select * from pedidosTotalesTodosDatos where idContacto="+idClient+";");
        try{
            while(res.next()){
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));

                model.addRow(v);
                orderList.setModel(model);
            }
        }catch(SQLException e){
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JTable();
        clientModuleBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        orderNumber = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idContact = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        province = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        employeeName = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Consult");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        orderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Order number", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderList);

        clientModuleBack.setText("Back");
        clientModuleBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientModuleBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Order number");

        orderNumber.setText("jLabel2");

        jLabel3.setText("Date");

        date.setText("jLabel4");

        jLabel5.setText("Type");

        type.setText("jLabel6");

        jLabel7.setText("Status");

        status.setText("jLabel8");

        jLabel9.setText("Employeer name");

        idContact.setText("jLabel10");

        jLabel11.setText("Contact ID");

        province.setText("jLabel12");

        jLabel13.setText("Province");

        employeeName.setText("jLabel14");

        jLabel15.setText("Medicines");

        jLabel16.setText("Price");

        price.setText("jLabel17");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Medicine", "Image", "Unities"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel18.setText("Consult Information About Orders");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clientModuleBack)
                        .addGap(226, 226, 226)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(352, 352, 352)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16))
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderNumber)
                    .addComponent(date)
                    .addComponent(type)
                    .addComponent(status)
                    .addComponent(idContact)
                    .addComponent(province)
                    .addComponent(employeeName)
                    .addComponent(price))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientModuleBack)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel1)
                            .addComponent(orderNumber))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(type)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(status))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idContact)
                            .addComponent(jLabel11))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(province)
                    .addComponent(jLabel13))
                .addGap(4, 4, 4)
                .addComponent(jLabel15)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeName)
                    .addComponent(jLabel9))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(price))
                .addGap(220, 220, 220))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientModuleBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientModuleBackActionPerformed
        // TODO add your handling code here:
        signIn signInAccess = new signIn();
        signInAccess.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clientModuleBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = orderList.getSelectedRow();
        String numberOrder = orderList.getValueAt(row, 0).toString();
        try {
            res = ConnectionSQL.createConsult("select * from pedidosTotalesTodosDatos where idPedido="+numberOrder+";");
            while (res.next()) {
                orderNumber.setText(Integer.toString(res.getInt(1)));
                date.setText(res.getString(2));
                idContact.setText(res.getString(6));
            }
            res=ConnectionSQL.createConsult("select A.* from tipoPedido A inner join pedidosTotalesTodosDatos B on A.idTipoPedido=B.tipoPedido and B.idPedido="+numberOrder+";");
            while (res.next()) {
                type.setText(res.getString(2));
            }
            res=ConnectionSQL.createConsult("select A.* from estadoPedido A join pedidosTotalesTodosDatos B on A.idEstadoPedido=B.estadoPedido and B.idPedido="+numberOrder+";");
            while (res.next()) {
                status.setText(res.getString(2));
            }
            res=ConnectionSQL.createConsult("select sum(A.precio * B.cantidad) from medicamento as A join medicamentoPedidosTotales as B on A.idMedicamento=B.idMedicamento join pedidosTotalesTodosDatos as C on B.idPedido=C.idPedido and C.idPedido="+numberOrder+";");
            while (res.next()) {
                price.setText("$"+Double.toString(res.getDouble(1)));
            }
            res=ConnectionSQL.createConsult("select A.nombre from empleadosTotales A join pedidosTotalesTodosDatos B on A.cedula=B.cedulaEmpleado and B.idPedido="+numberOrder+";");
            while (res.next()) {
                employeeName.setText(res.getString(1));
            }
            res=ConnectionSQL.createConsult("select C.provincia from farmaciasTotales A join pedidosTotalesTodosDatos B on A.cedulaJuridica=B.cedulaJuridica join provincia C on A.idProvincia=C.idProvincia and B.idPedido="+numberOrder+";");
            while (res.next()) {
                province.setText(res.getString(1));
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(clientModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(clientModule.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new clientModule().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(clientModule.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientModuleBack;
    private javax.swing.JLabel date;
    private javax.swing.JLabel employeeName;
    private javax.swing.JLabel idContact;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable orderList;
    private javax.swing.JLabel orderNumber;
    private javax.swing.JLabel price;
    private javax.swing.JLabel province;
    private javax.swing.JLabel status;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
